### ISSUE TITLE
License on the dataset itself?

### ISSUE THREAD

**Issue by hughperkins** [rkadlec/ubuntu-ranking-dataset-creator#21]
Hi, 

What is the license on the dataset itself?

**Comment by rkadlec** [comment]
Good question, @ryan-lowe knows more about the source data used by this script.

**Comment by ryan-lowe** [comment]
Hi Hugh,
We obtained the original data from the Ubuntu Chat Corpus. The webpage is here: http://daviduthus.org/UCC/. It doesn't explicitly say the original license that I can see ---  I'd maybe read through their AAAI paper, and contact Uthus & Aha if it isn't there!

**Comment by hughperkins** [comment]
cool. Thanks!
