### ISSUE TITLE
Dialog .\dialogs\17\13318.tsv was shorter than the minimum required lenght 1

### ISSUE THREAD

**Issue by ranjita-naik** [rkadlec/ubuntu-ranking-dataset-creator#27]
python create_ubuntu_dataset.py  --output "train.csv" "train"

is failing with the above error. Anybody else facing this issue?

**Comment by ranjita-naik** [comment]
I managed to resolve it by re-sampling instead of exiting when the dialog_len<min_turn. Specifically,  the following lines of code in the function - get_random_utterances_from_corpus :

if(dialog_len<min_turn): 
       print "Dialog {} was shorter than the minimum required lenght {}".format(dialog_path,dialog_len) 
       exit()

**Comment by snigdha0109** [comment]
we are having same issue what should be done
