### ISSUE TITLE
Created Training set is smaller than the old one & error with create_eval_dataset function

### ISSUE THREAD

**Issue by Ahmed-Abouzeid** [rkadlec/ubuntu-ranking-dataset-creator#5]
Please advice:
1- the code below contains a modified parameters default=10250000 so we can extract more training examples, right? because if I used only 1000000 it gives me smaller training set compared to the one from the original dataset, what if I want the same number of examples from the old training set, what should be the default=?? , in other words how many examples are in the training set?

2- the code below, which related to the test and eval sets is giving error in run time saying that: AttributeError: 'Namespace' object has no attribute 'examples' ,
 kindly advice if that was popular for you.

parser_train = subparsers.add_parser('train', help='trainset generator')
    parser_train.add_argument('-p', type=float, default=0.5, help='positive example probability')
    parser_train.add_argument('-e', '--examples', type=int, default=10250000, help='number of examples to generate')
    parser_train.set_defaults(func=train_cmd)

```
parser_test = subparsers.add_parser('test', help='testset generator')
parser_test.add_argument('-n', type=int, default=9, help='number of distractor examples for each context')
parser_test.set_defaults(func=test_cmd)

parser_valid = subparsers.add_parser('valid', help='validset generator')
parser_valid.add_argument('-n', type=int, default=9, help='number of distractor examples for each context')
parser_valid.set_defaults(func=valid_cmd)
```

**Comment by rkadlec** [comment]
Hi, 
1) I would stay with 1M training examples as default. This new dataset is generated in a different way compared to the previous dataset v1 so the performance of classifiers trained on this data wont match the previous results anyway.
2) this bug was probably introduced in my previous commit, sorry, I will fix it

**Comment by Ahmed-Abouzeid** [comment]
Thank you!

**Comment by rkadlec** [comment]
You are welcome. 
The  #issue was fixed in the last commit.
